### ISSUE TITLE
Describe in detail the system requirements.

### ISSUE THREAD

**Issue by tanaka-hiroki1989** [kiharalab/DOVE#4]
We want the following to be written in the README.

- An OS that is confirmed to work with DOVE
- The required Python version.
- Test results with more recent versions of each library.

Best regards.

**Comment by tanaka-hiroki1989** [comment]
Additional questions.

Is the required Tensorflow version 0.12 instead of 1.12?

Best regards.

**Comment by wang3702** [comment]
Thanks a lot for your question!
First, for the OS, we highly suggest use linux based system, such as Ubuntu.
Second, for python, we think python3.5 is a good choice.
Third, we did not try on new version of library. I don't think it can run on new version because of some functions may be deprecated after updates.
Yes. please use 0.12 tensorflow.

**Comment by tanaka-hiroki1989** [comment]
@wang3702 Thank you very much for your comment !
